### ISSUE TITLE
Reflow code with Black

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/api#128]

**Comment by SaptakS** [comment]
I would like to work on this issue. The main purpose of this issue is to restructure and lint code by running black, right?

**Comment by FedericoCeratto** [comment]
@SaptakS yes, it's just a matter of running `for i in **/*.py;do  black $i; done` in the repo and send a PR. It should produce very few changes.

**Comment by SaptakS** [comment]
@FedericoCeratto Yes. That's what I had in mind. Just wanted to confirm. I will send in a PR for the same if no one else is working.
