### ISSUE TITLE
Discuss/research next steps in relation to database performance

### ISSUE THREAD

**Issue by hellais** [ooni/api#135]
We should have a dedicated meeting to plan work that has to be done as part of: https://github.com/ooni/api/issues/116.

The goal for this meeting is to have an initial investigation and see what are the usages currently for OONI Explorer.

**Comment by FedericoCeratto** [comment]
Update: discussed strategies for DB update to PG 11.5 or 12 with minimum impact. Run simple benchmarks on queries. Currently pending a reply on availability of hardware in AMS.

**Comment by hellais** [comment]
We did some progress on this yesterday with @FedericoCeratto 

Specifically we added some metrics that tell us which are the slowest queries in prometheus and based on that were able to identify some low hanging fruit for optimisation which we fixed here:
https://github.com/ooni/api/pull/137
https://github.com/ooni/api/pull/138

It was deployed to the production API in https://github.com/ooni/sysadmin/commit/89292d53cbdda5b0896f99fd7d2c4c839908c62d and we should check the monitoring to see if the performance is a bit better.

**Comment by FedericoCeratto** [comment]
The database metric generator is in https://github.com/ooni/pipeline/pull/205 
It's producing http://fastpath.ooni.nu:8080/analysis/db_slow_queries_standby.html and http://fastpath.ooni.nu:8080/analysis/db_slow_queries_active.html every hour

**Comment by FedericoCeratto** [comment]
Also created https://mon.ooni.nu/grafana/d/FNVKM2-Wk/api-and-amsdb?orgId=1

**Comment by FedericoCeratto** [comment]
Also investigating performance in https://github.com/ooni/api/issues/142

**Comment by hellais** [comment]
Discussions were had, plans were made and PRs are ready to be merged.
