### ISSUE TITLE
​/api​/v1​/aggregation doesn't take test_name into account?

### ISSUE THREAD

**Issue by cyBerta** [ooni/api#203]
When fetching aggregated data, the test_name query seems not to be taken into account.

for example 
`curl -X GET "https://api.ooni.io/api/v1/aggregation?test_name=dns_consistency&since=2020-10-30T00%3A00%3A00&until=2020-11-25T00%3A00%3A00&axis_y=probe_cc&format=JSON" -H  "accept: application/json"`

results in the same output as 

`curl -X GET "https://api.ooni.io/api/v1/aggregation?test_name=vanilla_tor&since=2020-10-30T00%3A00%3A00&until=2020-11-25T00%3A00%3A00&axis_y=probe_cc&format=JSON" -H  "accept: application/json"`

This seems to be a bug to me.

**Comment by hellais** [comment]
Thanks for reporting this! You are right that this is a bug. We are tracking it through the following issue in `ooni/backend`: https://github.com/ooni/backend/issues/480
