### ISSUE TITLE
Performance improvements to ooni-measurements API endpoints

### ISSUE THREAD

**Issue by hellais** [ooni/api#26]
Currently the ooni-measurements API backed by ooni-pipeline (see: https://github.com/TheTorProject/ooni-measurements/pull/22) is quite slow in some of the queries.

What we were doing as a workaround in the "legacy" version of it (that with it's own database) was using the `flask_cache` module to do an in memory cache of some of the API endpoints (mainly those for showing the stats), but that actually is kind of a hack as in production we are running it with 4 workers, hence the cache is likely to be stale if the user hits one of the workers that hasn't cached it yet.

To this end what I think would be useful to do is:

* [ ] Profile the various API endpoints to find which common queries are taking too long (ooni-measurements will actually already log this by default: https://github.com/TheTorProject/ooni-measurements/blob/0eed3db2d83e0cadffd09b158f4ae88ce70f5aa9/measurements/database.py#L34, but postgres also can do this)
* [ ] Define some materialized views inside of ooni-pipeline to cache these views
* [ ] Refactor ooni-mesurements to query the mat-views instead of running the actual queries

**Comment by hellais** [comment]
A query worth looking into making faster is one in the lines of:

```
EXPLAIN ANALYZE SELECT measurement.input_no AS m_input_no,
  measurement.measurement_start_time AS measurement_start_time,
  measurement.msm_no AS msm_no, measurement.report_no AS m_report_no,
  coalesce(label.anomaly, measurement.anomaly, false) AS anomaly,
  coalesce(label.confirmed, measurement.confirmed, false) AS confirmed,
  coalesce(label.msm_failure, measurement.msm_failure, false) AS msm_failure,
  measurement.exc AS exc,
  measurement.residual_no AS residual_no,
  report.report_id AS report_id, report.probe_cc AS probe_cc,
  report.probe_asn AS probe_asn,
  report.test_name AS test_name,
  report.report_no AS report_no,
  coalesce(input.input, NULL) AS input
FROM measurement JOIN report ON report.report_no = measurement.report_no
  LEFT OUTER JOIN label ON label.msm_no = measurement.msm_no
  LEFT OUTER JOIN input ON measurement.input_no = input.input_no
WHERE report.probe_cc = 'IT' AND measurement.measurement_start_time > '2017-09-01'
      AND coalesce(label.confirmed, measurement.confirmed, false) = true
 LIMIT 100 OFFSET 0;
```

**Comment by darkk** [comment]
I'd remind that same "templated" query may have different execution plans depending on input values (I was caught by that pitfall couple of times). E.g. plan may be different for `probe_cc = 'IT'` and `probe_cc = 'ZZ'`.

Also, plan is selected based on `*_cost`, but current setup has r/w database on HDD in HKG and r/o replica on SSD in AMS, so cost settings differ. In some cases it _may_ be handy to create unlogged tables on r/w copy and set cost variables just for the current session while doing experiments to improve SELECT plans.

**Comment by darkk** [comment]
I'd also point out that few legacy URLs to data files have suboptimal performance in some cases. Those are there since #44 to preserve old links to ooni-measurements via `http://measurements.ooni.torproject.org/` and `http://measurements.ooni.io/` URLs. BTW, those domains are currently down.

E.g. `files_download(textname)` in `https://github.com/ooni/api/blob/master/measurements/pages/__init__.py#L283-L294` takes ~4.5s for a non-existing URLs like http://api.ooni.io/files/download/nonexistent.json

It's unclear to me if it's worth fixing or not, it's probably not the only way to DoS API, so I'm just writing the issue down for completeness.

**Comment by hellais** [comment]
Closing this in favour of all the issues labeled optimisation: https://github.com/ooni/api/issues?q=is%3Aopen+is%3Aissue+label%3Aoptimization.
