### ISSUE TITLE
Change name to OONI API

### ISSUE THREAD

**Issue by elioqoshi** [ooni/api#34]
From our Slack chat with @hellais, we were considering to change the name of OONI Measurements to OONI API. 

The reasons for this are several:

- Measurements is a quite long word (12 letters) and looks rather odd compared to other tools (OONI Run) and it gathers too much attention in branding as well (whereas OONI should be the focus)
- The URL is quite long to type ( measurements.ooni.torproject.org )
- The API is in fact the highlight anyway. API would clarify what it is easily without much confusion.

![ooni api](https://user-images.githubusercontent.com/5436686/30491515-d023553c-9a3d-11e7-9687-7b8dab90b910.jpg)

What do you think?

**Comment by hellais** [comment]
This is done in the app, but I am leaving this open so we remember to change the name on the website too.

**Comment by gabelula** [comment]
It seems that this is already done, right? Let's close it.

**Comment by hellais** [comment]
Yes you are right. This was done here: https://github.com/TheTorProject/ooni-web/pull/182
