### ISSUE TITLE
Mutli-value parameters for measurements API

### ISSUE THREAD

**Issue by darkk** [ooni/api#35]
API may have parameters accepting list of values (e.g `anomaly: [true, false]`). That may have several representations in QUERY_STRING.

Human-friendly representation is `/handle?anomaly=true,false&other=arg`, it's only valid for values that are integers and booleans. And, maybe, floats. I suggest to avoid adding floats to prevent confusion like `v=1,2` vs. `v=1.2'. Strings can't have `,` as it'll lead to awful escaping rules.

Machine-friendly representation is `/handle?anomaly=true&anomaly=false&other=arg`, it's valid for values of any type. [`urlparse.parse_qsl()`](https://docs.python.org/2/library/urlparse.html#urlparse.parse_qs) parses that format, it's quite standart.

**Comment by hellais** [comment]
I believe this is supported in the current version of the API. Is there anything else you would like to see supported?

**Comment by hellais** [comment]
Closing this
