### ISSUE TITLE
Fix link for API docs

### ISSUE THREAD

**Issue by agrabeli** [ooni/api#57]
Currently when you click on "API docs" (in the API page: https://api.ooni.io/) you get https://api.ooni.io/api, which doesn't work. It needs to redirect to https://api.ooni.io/api/.

**Comment by darkk** [comment]
That's fun, redirect without Location header.
```
< HTTP/1.1 301 MOVED PERMANENTLY
< Server: nginx/1.12.2
< Date: Mon, 16 Jul 2018 14:02:29 GMT
< Content-Type: application/problem+json
< Content-Length: 95
< Connection: keep-alive
< Keep-Alive: timeout=120
< Access-Control-Allow-Origin: *
< 
{
  "detail": null,
  "status": 301,
  "title": "Moved Permanently",
  "type": "about:blank"
}
```

**Comment by hellais** [comment]
In the latest master the links to the docs pages should be fixed.
