### ISSUE TITLE
Implement the missing required endpoints

### ISSUE THREAD

**Issue by gabelula** [ooni/api#61]
Implement the necessary endpoints to have the new version of OONI explorer up.

Related to 
- "Write specification for the current and future versions of the ooni-explorer API" https://github.com/ooni/api/issues/9
- "API Endpoints Design" https://github.com/ooni/api/issues/8

**Comment by hellais** [comment]
In order for this to happen, it would be great to have documentation on:

* [ ] How to add extractor to OONI Pipeline for new tests
* [ ] How to reprocess the data to put these metrics inside of the database

@darkk do you think you could write some docs on this?

**Comment by hellais** [comment]
This was completed as part of: https://github.com/ooni/api/pull/77.

Still some work is to be done for new tests, but this is good for an MVP.
