### ISSUE TITLE
API Endpoints Design

### ISSUE THREAD

**Issue by hellais** [ooni/api#8]
@simonv3 commented on [Fri Dec 04 2015](https://github.com/TheTorProject/ooni-explorer/issues/7)

Started a page for this: https://github.com/TheTorProject/ooni-api/wiki/API-Design

We can use this ticket to sketch out initial ideas. 

---

@TylerJFisher commented on [Sat Dec 05 2015](https://github.com/TheTorProject/ooni-explorer/issues/7#issuecomment-162256108)

Updated: https://github.com/TheTorProject/ooni-api/wiki/API-Design

---

@hellais commented on [Sun Dec 06 2015](https://github.com/TheTorProject/ooni-explorer/issues/7#issuecomment-162321362)

Very good job on the API specification.

Just to be clear that I understand some things about it.

Your suggestion is to place all the test specific keys inside of the `test_keys` value (using the JSON feature of PostgreSQL) of the `Metrics` table and to generate some test specific views (that assess what Metrics present anomalies) based on some PgSQL procedures that get run in batch.
Is this accurate?

---

@TylerJFisher commented on [Sun Dec 06 2015](https://github.com/TheTorProject/ooni-explorer/issues/7#issuecomment-162336467)

Thanks, @hellais! That's correct - in order to implement this I'd likely opt to use a trigger within either PostgreSQL, or within middleware somewhere (e.g. ooni-pipeline using an ORM framework). The goal behind explicitly separating _common_ and _test-specific_ keys is to allow for test-specific tables, and views to be created.

**Comment by gabelula** [comment]
@hellais Is this a ticket we can close?

**Comment by hellais** [comment]
Yes I guess this is superseeded by #61 .
